### PR TITLE
adding my notebook

### PR DESCRIPTION
**Pull request by gtfierro**
Description provided

### CODE REVIEW

**Comment by SoniaSpindt** [comment]
Anything in particular that you want me to focus on?

**Comment by gtfierro** [comment]
> Anything in particular that you want me to focus on?

Nope! Just work your magic

**Review by SoniaSpindt — CHANGES_REQUESTED** [review]
Lol We're focusing on clustering, so take a look at DBSCAN instead.

**Review by SoniaSpindt — APPROVED** [review]
Awesome! Thanks for the change. Looks good. Fingers crossed, DB works.

**Pull request merged**
